# Generated by Django 2.1.7 on 2019-03-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='LifeCicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=300, verbose_name='Fase')),
                ('march', models.CharField(max_length=300, verbose_name='Marco')),
            ],
            options={
                'verbose_name': 'Ciclo de Vida',
                'verbose_name_plural': 'Ciclos de Vida',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Produto ou Serviço',
                'verbose_name_plural': 'Produtos ou Serviços',
            },
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Timestamp')),
                ('name', models.CharField(max_length=1000, verbose_name='Nome ou Sigla')),
                ('escopo', models.TextField()),
                ('eap', models.ImageField(upload_to='EAP', verbose_name='EAP')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data termino')),
                ('expected_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Orçamento previsto')),
                ('executed_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Orçamento executado')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Institution', verbose_name='instituicao')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
            bases=('core.timestamp',),
        ),
        migrations.AddField(
            model_name='productservice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='projeto'),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='projeto'),
        ),
        migrations.AddField(
            model_name='lifecicle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='projeto'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='projeto'),
        ),
    ]
