# Generated by Django 2.1.7 on 2019-03-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='eap',
            field=models.ImageField(null=True, upload_to='EAP', verbose_name='EAP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Data termino'),
        ),
        migrations.AlterField(
            model_name='project',
            name='escopo',
            field=models.TextField(null=True, verbose_name='Escopo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='executed_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento executado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='expected_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento previsto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Data início'),
        ),
    ]
