# Generated by Django 2.1.7 on 2019-03-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190315_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fechamento do projeto'),
        ),
    ]
