# Generated by Django 2.1.7 on 2019-03-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='eap',
            field=models.FileField(blank=True, null=True, upload_to='EAP', verbose_name='EAP'),
        ),
    ]
