# Generated by Django 2.1.7 on 2019-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190329_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholders',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('A', 'Andamento'), ('C', 'Concluido'), ('P', 'Em Planejamento'), ('E', 'Encerrado')], default='A', max_length=1, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Stakeholders',
        ),
    ]
